#!/bin/sh

~/.fehbg &

xsetroot -cursor_name left_ptr
setxkbmap -option compose:menu

picom -r 10 -o 0.75 -l -10 -t -10 -m 1.0 -D 3 &
light-locker &
easyeffects --gapplication-service &
wired &
polybar main &
nm-applet &
blueman-applet &
xfce4-clipman &
steam -silent &
discord --start-minimized &
syncthing serve --no-browser &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          2
bspc config window_gap            6

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
