#!/bin/sh

~/.fehbg &

# Xorg config
xsetroot -cursor_name left_ptr &
setxkbmap -option compose:menu

# Keybinds
pgrep -x sxhkd > /dev/null || sxhkd &

# BSPWM Config
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          2
bspc config window_gap            8

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config active_border_color "#0c0e14"
bspc config focused_border_color "#73d0ff"
bspc config normal_border_color "#b77ee0"

# Fix for spotify rules:
bspc config external_rules_command $HOME/.config/bspwm/scripts/custom_rules.sh

# Rules
bspc rule -a mpv state=floating sticky=on locked=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a obsidian desktop='^7'
bspc rule -a Steam desktop='^8' follow=off focus=off
bspc rule -a discord desktop='^9'

# Autostart
lxpolkit & # polkit auth agent
sh ~/.screenlayout/monitor.sh & # arandr
picom -CGb & # compositor
wired & # notifications
~/.config/polybar/launch.sh & #TODO: spotify
/usr/lib/geoclue-2.0/demos/agent & # geoclue (for redshift)
easyeffects --gapplication-service & # mic noise reduction
syncthing serve --no-browser & # file sync

# Delayed
sleep 3
redshift-gtk & # night mode
nm-applet & # networks tray icon
blueman-applet & # bluetooth tray icon
steam -silent & # steam
discord --start-minimized & # discord

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
